version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/PiWol.WebApp/ClientApp"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/tools/license-extractor"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
