version: '#{build}'
image: 
  - Ubuntu2004
init:
  - git config --global core.autocrlf input
  - sh: |
      mkdir ~/.docker
      echo "{ \"experimental\": \"enabled\" }" > ~/.docker/config.json
  - sh: dotnet tool install --global GitVersion.Tool --version 5.6.4
stack: node 15

install:
  - sh: chmod +x buildscript/build.sh

environment:
  IS_CI_BUILD: true
  DOCKER_CI_USER:
    secure: 12oDQF2cCY1ti+AjmwopSA==
  DOCKER_CI_PASSWORD:
    secure: uMe6MgbnQrXPleWxkBEAOzwZL1YIKKiYsPi3kxFndYM=
  DOCKER_REPO: chtake/pi-wol

build_script:
  - sh: ./buildscript/build.sh build

test_script:
  - sh: ./buildscript/build.sh test

artifacts:
  - path: 'artifacts/*.zip'

before_deploy:
  - sh: docker login -u ${DOCKER_CI_USER} -p ${DOCKER_CI_PASSWORD}

on_finish:
  - sh: find "${APPVEYOR_BUILD_FOLDER}/test-results" -type f -name '*.trx' -print0
  - sh: |
      find "${APPVEYOR_BUILD_FOLDER}/test-results" -type f -name '*.trx' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/mstest/$APPVEYOR_JOB_ID"

for:
-
  branches:
    only:
      - develop
  deploy_script:
      - sh: ./buildscript/build.sh deploy_develop
-
  branches:
    only:
      - master
  deploy:
    - provider: GitHub
      artifact: /.*\.zip/
      draft: false
      prerelease: false
      auth_token:
        secure: DP0SA4jTvTlDok+oGUpw4OhXnnIGrk8+tMWAp9w+oBEXG9u1wWWV7S+DwGBxOjXF
      on:
        APPVEYOR_REPO_TAG: true
  before_deploy:
    - sh: docker login -u ${DOCKER_CI_USER} -p ${DOCKER_CI_PASSWORD}
    - sh: ./buildscript/build.sh deploy_release
