FROM mcr.microsoft.com/dotnet/core/runtime:2.2-bionic

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y net-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY publish .

VOLUME ["/app/data"]
EXPOSE 80/tcp

ENTRYPOINT [ "dotnet", "PiWol.WebApp.dll" ]