### This workflow doesn't have access to secrets and has a read-only token
name: "Dependabot push check"
on:
  push:
    branches: [ develop ]

jobs:
  check-dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - run: echo "Pushed by Dependabot"
